/**
 * Generated by quail.
 *
 * Verifies that pasting HTML content (including scripts) into a text input on the mortgage calculator page does not execute scripts — i.e., HTML is sanitized and not rendered as live markup.
 *
 * Filter: `npx playwright test --grep @kind:clipboard`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('Ing — clipboard @ https://www.ing.nl/en/personal/mortgage/mortgage-calculator', () => {
  test('pasting HTML with inline scripts into text input is sanitized', async ({ page, context }) => {
    await context.grantPermissions(['clipboard-read', 'clipboard-write']).catch(() => {})
    await page.goto('/en/personal/mortgage/mortgage-calculator', { waitUntil: 'domcontentloaded' })
    const input = page.locator('input[type="text"], input[type="search"], input:not([type]), textarea').first()
    if (await input.count() === 0) test.skip()
    await input.focus()
    // Simulate paste of a content with an HTML payload + an inline
    // script. Real clipboard APIs vary by OS; we use evaluate to
    // dispatch a paste event the page can intercept.
    const payload = '<img src=x onerror="window.__pasteXSS=true" />HELLO'
    await input.evaluate((el, p) => {
      const event = new ClipboardEvent('paste', {
        clipboardData: new DataTransfer(),
        bubbles: true,
      })
      event.clipboardData!.setData('text/html', p)
      event.clipboardData!.setData('text/plain', p)
      el.dispatchEvent(event)
      ;(el as HTMLInputElement).value = p
    }, payload)
    // The value should contain the literal text, NOT have executed the script.
    const value = await input.inputValue()
    expect(value).toContain('HELLO')
    const xssFired = await page.evaluate(() => (window as any).__pasteXSS === true)
    expect.soft(xssFired, 'paste fired inline script — XSS vulnerability').toBe(false)
  })
})
