/**
 * Generated by quail.
 *
 * Verifies at least one standard health endpoint responds with 2xx. Returns a soft warning (no test failure) if none are available, since omitting health endpoints is valid.
 *
 * Filter: `npx playwright test --grep @kind:health`
 */
import { test, expect } from '@playwright/test'

const HEALTH_PATHS = ['/health', '/healthz', '/ready', '/readyz', '/status', '/livez']

test.describe.configure({ mode: 'parallel' })
describe('Ing — health probes @ https://www.ing.nl', () => {
  test('@kind:health @smoke at least one standard health endpoint responds with 2xx', async ({ request }) => {
    const results: Array<{ path: string; status: number }> = []
    for (const path of HEALTH_PATHS) {
      try {
        const url = new URL(path, 'https://www.ing.nl').toString()
        const r = await request.get(url, { timeout: 5_000, maxRedirects: 0 })
        results.push({ path, status: r.status() })
      } catch (e) {
        results.push({ path, status: -1 })
      }
    }
    log health probe results
    const anyHealthy = results.some(r => r.status >= 200 && r.status < 300)
    if (!anyHealthy) {
      console.log('no standard health endpoint responded 2xx — consider exposing /health or /healthz')
    }
    soft fail if no health endpoint responded 2xx
    // Hard fail only when EVERY probe errored (network down) — a 404 is
    // a perfectly valid response.
    const allErrored = results.every(r => r.status === -1)
    soft fail if all probes errored (origin unreachable?)
  })
})
