# Generated by reviewqa.
#
# Gherkin contract for the research journey on https://www.spritecloud.com.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:research
#   npx playwright test --grep @smoke

Feature: WwwSpritecloudCom — research journey
  As a visitor of https://www.spritecloud.com
  I want to complete the research flow
  So that the page delivers on its user goal

  @journey:research @priority:standard @smoke
  Scenario: research journey completes on the case study page
    Given I open the landing page
    And the page title contains "spriteCloud - Test your software, not your reputation!"
    And the main heading reads "Test your software, not your reputation."
    When I click the link to "/case-study-ecomm-platform"
    Then I see the heading "Performance Testing for an eCommerce Platform"
    And the page title contains "Case Study - eCommerce Platform"

  @journey:research @priority:standard @kind:resume
  Scenario: research — direct link to case study page loads properly
    Given I open the page "/case-study-ecomm-platform"
    Then I see the heading "Performance Testing for an eCommerce Platform"

  @journey:research @priority:standard @kind:back-button
  Scenario: research — using back button returns to the landing page
    Given I open the landing page
    When I click the link to "/case-study-ecomm-platform"
    When I go back in the browser history
    Then the main heading reads "Test your software, not your reputation."

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:research @priority:standard @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: User scrolls down to see the case studies section
    Given I am on the landing page
    When I scroll to the bottom of the page
    Then I see the heading "Case Studies"

  @journey:research @priority:standard @llm-composed @kind:variant @model:qwen3-coder-next-latest
  Scenario: User opens then closes the navigation menu
    Given I am on the landing page
    When I open the menu
    And I close the menu
    Then I remain on the same page
