# Generated by reviewqa.
#
# Gherkin contract for the research journey on https://www.spritecloud.com.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:research
#   npx playwright test --grep @smoke

Feature: WwwSpritecloudCom — research journey
  As a visitor of https://www.spritecloud.com
  I want to complete the research flow
  So that the page delivers on its user goal

  @journey:research @priority:standard @smoke
  Scenario: visitor completes research flow and lands on case study
    Given I open the landing page
    And the page title contains "spriteCloud - Test your software, not your reputation!"
    And the main heading reads "Test your software, not your reputation."
    When I click the link to "/case-study-ecomm-platform"
    Then I see the heading "Performance Testing for an eCommerce Platform"
    And the page title contains "Case Study - eCommerce Platform"

  @journey:research @priority:standard @kind:resume
  Scenario: deep-link to case study page loads and displays correctly
    Given I open the page "/case-study-ecomm-platform"
    Then I see the heading "Performance Testing for an eCommerce Platform"

  @journey:research @priority:standard @kind:back-button
  Scenario: back button navigation from case study returns to landing page
    Given I open the landing page
    When I click the link to "/case-study-ecomm-platform"
    When I go back in the browser history
    Then the main heading reads "Test your software, not your reputation."

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:research @priority:standard @llm-composed @kind:variant @model:qwen3-coder-next-latest
  Scenario: contact link navigates to contact page
    Given I am on the landing page
    When I click the link to "/contact"
    Then the URL contains "/contact"
    Then the main heading reads "Contact us"

  @journey:research @priority:standard @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: direct navigation to guides page works
    Given I open the page "/guides"
    Then the page title contains "Guides"
    Then I see the heading "Software Testing Guides"

  @journey:research @priority:standard @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: case studies section loads and visible at page bottom
    Given I am on the landing page
    When I scroll to the bottom of the page
    Then I scroll into view of the "Case Studies" element
    Then the page has at least 3 items
