# Generated by reviewqa.
#
# Gherkin contract for the explore journey on https://www.spritecloud.com.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:explore
#   npx playwright test --grep @smoke

Feature: WwwSpritecloudCom — explore journey
  As a visitor of https://www.spritecloud.com
  I want to complete the explore flow
  So that the page delivers on its user goal

  @journey:explore @priority:nice-to-have @smoke
  Scenario: explore journey completes on the terminal page
    Given I open the landing page
    And the page title contains "spriteCloud - Test your software, not your reputation!"
    And the main heading reads "Test your software, not your reputation."
    When I click the link to "/cybersecurity"
    Then I see the heading "Fully Tailored Cybersecurity."
    And the page title contains "spriteCloud - Penetration Testing"

  @journey:explore @priority:nice-to-have @kind:resume
  Scenario: explore — deep-linking to the terminal page shows the correct content
    Given I open the page "/cybersecurity"
    Then I see the heading "Fully Tailored Cybersecurity."

  @journey:explore @priority:nice-to-have @kind:back-button
  Scenario: explore — using the back button after navigation returns to the landing page
    Given I open the landing page
    When I click the link to "/cybersecurity"
    When I go back in the browser history
    Then the main heading reads "Test your software, not your reputation."

  @journey:explore @priority:nice-to-have @kind:cross-journey
  Scenario: explore — navigating to landing and back leaves the page intact
    Given I open the landing page
    When I navigate directly to "/"
    And I go back in the browser history
    Then no error message is shown in the form region

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:explore @priority:nice-to-have @llm-composed @kind:variant @model:qwen3-coder-next-latest
  Scenario: explore — guides section accessible
    Given I open the landing page
    When I click the link to "/guides"
    Then the page title contains "Guides"

  @journey:explore @priority:nice-to-have @llm-composed @kind:variant @model:qwen3-coder-next-latest
  Scenario: explore — case studies page loads
    Given I am on the landing page
    When I click the link to "/case-studies"
    Then the page title contains "Case Studies"

  @journey:explore @priority:nice-to-have @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: explore — scrolling to bottom shows expected content
    Given I open the landing page
    When I scroll to the bottom of the page
    Then the main heading reads "Test your software, not your reputation."
