# Generated by reviewqa.
#
# Gherkin contract for the read journey on https://www.spritecloud.com.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:read
#   npx playwright test --grep @smoke

Feature: SpriteCloud read journey
  As a visitor of https://www.spritecloud.com
  I want to complete the read flow
  So that the page delivers on its user goal

  @journey:read @priority:nice-to-have @smoke
  Scenario: Visitor completes the read flow and lands on the correct page
    Given I open the landing page
    And the page title contains "spriteCloud - Test your software, not your reputation!"
    And the main heading reads "Test your software, not your reputation."
    When I navigate directly to "/book-performance-test"
    Then I see the heading "Performance Test"
    And the page title contains "Book - Performance Test"

  @journey:read @priority:nice-to-have @kind:resume
  Scenario: Reader navigates directly to the terminal page and sees correct content
    Given I open the page "/book-performance-test"
    Then I see the heading "Performance Test"

  @journey:read @priority:nice-to-have @kind:back-button
  Scenario: Reader uses browser back to return from terminal to landing page
    Given I open the landing page
    When I click the link to "/book-performance-test"
    When I go back in the browser history
    Then the main heading reads "Test your software, not your reputation."

  @journey:read @priority:nice-to-have @kind:cross-journey
  Scenario: Reader navigates between landing and terminal pages without errors
    Given I open the landing page
    When I navigate directly to "/"
    And I go back in the browser history
    Then no error message is shown in the form region
