# Generated by reviewqa.
#
# Gherkin contract for the read journey on https://www.spritecloud.com.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:read
#   npx playwright test --grep @smoke

Feature: WwwSpritecloudCom — read journey
  As a visitor of https://www.spritecloud.com
  I want to complete the read flow
  So that the page delivers on its user goal

  @journey:read @priority:nice-to-have @smoke
  Scenario: read journey ends on the expected page
    Given I open the landing page
    And the page title contains "spriteCloud - Test your software, not your reputation!"
    And the main heading reads "Test your software, not your reputation."
    When I navigate directly to "/style-guide"
    Then I see the heading "Aa"
    And the page title contains "Style Guide - Healix Webflow website HTML template"

  @journey:read @priority:nice-to-have @kind:resume
  Scenario: deep-linking directly to the style guide page loads it properly
    Given I open the page "/style-guide"
    Then I see the heading "Aa"

  @journey:read @priority:nice-to-have @kind:back-button
  Scenario: navigating to the style guide and pressing back returns to the landing page
    Given I open the landing page
    When I click the link to "/style-guide"
    When I go back in the browser history
    Then the main heading reads "Test your software, not your reputation."

  @journey:read @priority:nice-to-have @kind:cross-journey
  Scenario: switching between landing and root path and using back keeps state intact
    Given I open the landing page
    When I navigate directly to "/"
    And I go back in the browser history
    Then no error message is shown in the form region

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:read @priority:nice-to-have @llm-composed @kind:variant @model:qwen3-coder-next-latest
  Scenario: contact link on landing page is clickable and points to /contact
    Given I am on the landing page
    When I click the link to "/contact"
    Then the URL contains "/contact"

  @journey:read @priority:nice-to-have @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: scrolling to bottom shows at least five page items
    Given I am on the landing page
    When I scroll to the bottom of the page
    Then the page has at least 5 items

  @journey:read @priority:nice-to-have @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: opening and closing the navigation menu works without error
    Given I am on the landing page
    When I open the menu
    When I close the menu
