# Generated by quail.
#
# Gherkin contract for the browse journey on https://www.ing.nl/particulier/hypotheek/hypotheek-berekenen.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/quail.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:browse
#   npx playwright test --grep @smoke

Feature: Ing — browse journey
  As a visitor of https://www.ing.nl/particulier/hypotheek/hypotheek-berekenen
  I want to complete the browse flow
  So that the page delivers on its user goal

  @journey:browse @priority:standard @smoke
  Scenario: browse journey reaches its terminal page
    Given I open the landing page
    And the page title contains "Hypotheek berekenen juni 2026 - ING"
    And the main heading reads "Hypotheek berekenen"
    When I click the link to "/particulier"
    And the page title contains "Particulier - ING"
    When I click the link to "/zakelijk"
    Then I see the heading "Op naar je eerste miljoen. Dennis' groei ging in stappen"
    And the page title contains "ING Zakelijk voor ondernemers, bedrijven en organisaties - ING"

  @journey:browse @priority:standard @kind:empty-state
  Scenario: browse — page renders the landing list
    Given I open the landing page
    Then the page has at least 1 items

  @journey:browse @priority:standard @kind:resume
  Scenario: browse — deep-link to the terminal page renders correctly
    Given I open the page "/zakelijk"
    Then I see the heading "Op naar je eerste miljoen. Dennis' groei ging in stappen"

  @journey:browse @priority:standard @kind:back-button
  Scenario: browse — back button after navigation returns to landing
    Given I open the landing page
    When I click the link to "/zakelijk"
    When I go back in the browser history
    Then the main heading reads "Hypotheek berekenen"

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:browse @priority:standard @llm-composed @kind:variant @model:qwen3-coder-next-latest
  Scenario: reload_mid_form_retains_valid_data
    Given I am on the landing page
    When I enter "250000" into the "Hypotheekbedrag" field
    When I enter "30" into the "Looptijd in jaren" field
    When I reload the page
    Then the "Hypotheekbedrag" field has the value "250000"
    And the "Looptijd in jaren" field has the value "30"

  @journey:browse @priority:standard @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: submit_twice_no_double_calc
    Given I am on the landing page
    When I enter "250000" into the "Hypotheekbedrag" field
    When I enter "30" into the "Looptijd in jaren" field
    When I submit the form twice in rapid succession
    Then the form is not double-submitted

  @journey:browse @priority:standard @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: click_particulier_link_navigates_to_brand_page
    Given I am on the landing page
    When I click the link to "/particulier"
    Then the page title contains "Particulier - ING"
    Then the URL contains "/particulier"
