# Generated by quail.
#
# Gherkin contract for the exercise journey on https://www.spritecloud.com/test-automation.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/quail.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:exercise
#   npx playwright test --grep @smoke

Feature: Spritecloud — exercise journey
  As a visitor of https://www.spritecloud.com/test-automation
  I want to complete the exercise flow
  So that the page delivers on its user goal

  @journey:exercise @priority:standard @smoke
  Scenario: exercise journey reaches its terminal page
    Given I open the landing page
    And the page title contains "Test Automation"
    And the main heading reads "Expert Test Automation Services"

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:exercise @priority:standard @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: Reload mid-form keeps focus state
    Given I open the landing page
    When I focus the "contact-form-name" field
    When I enter "John Doe" into the "contact-form-name" field
    When I reload the page
    Then the "contact-form-name" field has the value "John Doe"

  @journey:exercise @priority:standard @llm-composed @kind:variant @model:qwen3-coder-next-latest
  Scenario: Rapid form submit prevents doubleSubmission
    Given I open the landing page
    When I submit the form twice in rapid succession
    Then the form is not double-submitted

  @journey:exercise @priority:standard @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: Form submit without required field shows no success
    Given I open the landing page
    When I submit the form without filling any required field
    Then no success message is shown
    Then I remain on the same page
