# Generated by quail.
#
# Gherkin contract for the exercise journey on https://www.spritecloud.com/.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/quail.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:exercise
#   npx playwright test --grep @smoke

Feature: Spritecloud — exercise journey
  As a visitor of https://www.spritecloud.com/
  I want to complete the exercise flow
  So that the page delivers on its user goal

  @journey:exercise @priority:standard @smoke
  Scenario: exercise journey reaches its terminal page
    Given I open the landing page
    And the page title contains "spriteCloud - Test your software, not your reputation!"
    And the main heading reads "Test your software, not your reputation."

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:exercise @priority:standard @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: Submit contact form twice rapidly
    Given I am on the landing page
    When I click the link to "/contact"
    When I submit the form twice in rapid succession
    Then the form is not double-submitted
    Then no success message is shown

  @journey:exercise @priority:standard @llm-composed @model:qwen3-coder-next-latest
  Scenario: Navigate to contact → submit empty → stay on page
    Given I am on the landing page
    When I click the link to "/contact"
    When I submit the form without filling any required field
    Then I remain on the same page
    Then no error message is shown in the form region
