# Generated by quail.
#
# Gherkin contract for the exercise journey on https://www.spritecloud.com/.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/quail.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:exercise
#   npx playwright test --grep @smoke

Feature: Spritecloud — exercise journey
  As a visitor of https://www.spritecloud.com/
  I want to complete the exercise flow
  So that the page delivers on its user goal

  @journey:exercise @priority:standard @smoke
  Scenario: exercise journey reaches its terminal page
    Given I open the landing page
    And the page title contains "spriteCloud - Test your software, not your reputation!"
    And the main heading reads "Test your software, not your reputation."
