# Generated by quail.
#
# Gherkin contract for the research journey on https://www.spritecloud.com/.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/quail.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:research
#   npx playwright test --grep @smoke

Feature: Spritecloud — research journey
  As a visitor of https://www.spritecloud.com/
  I want to complete the research flow
  So that the page delivers on its user goal

  @journey:research @priority:standard @smoke
  Scenario: research journey reaches its terminal page
    Given I open the landing page
    And the page title contains "spriteCloud - Test your software, not your reputation!"
    And the main heading reads "Test your software, not your reputation."
    When I navigate directly to "/case-studies/citizenm"
    Then I see the heading "Case Study"
    And the page title contains "spriteCloud - Your Software Testing and QA partner"

  @journey:research @priority:standard @kind:resume
  Scenario: research — deep-link to the terminal page renders correctly
    Given I open the page "/case-studies/citizenm"
    Then I see the heading "Case Study"

  @journey:research @priority:standard @kind:back-button
  Scenario: research — back button after navigation returns to landing
    Given I open the landing page
    When I click the link to "/case-studies/citizenm"
    When I go back in the browser history
    Then the main heading reads "Test your software, not your reputation."

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:research @priority:standard @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: Submit contact form twice
    Given I am on the landing page
    When I click the link to "/contact"
    Then the main heading reads "Contact Us"
    When I submit the form twice in rapid succession
    Then the form is not double-submitted

  @journey:research @priority:standard @llm-composed @kind:variant @model:qwen3-coder-next-latest
  Scenario: Reload contact page mid-fill
    Given I am on the landing page
    When I click the link to "/contact"
    Then the main heading reads "Contact Us"
    When I enter "test@example.com" into the "Email" field
    When I reload the page
    Then the "Email" field has the value "test@example.com"
