// Generated by quail. Shared Playwright fixtures for the generated
// e2e suite. All `*.spec.ts` files in this directory import `test` and
// `expect` from here instead of from `@playwright/test` directly, so
// every spec inherits the page-error tracking + baseline assertions
// without re-declaring them.
import { test as base, expect } from '@playwright/test'

// pageErrors is a custom fixture built around the standard `page`
// fixture. It captures JavaScript errors using a `pageerror` listener at the start of each
// test and verifies the captured list is empty at the end.
//
// `expect.soft` is used for the final assertion so any uncaught JavaScript
// error is reported without failing subsequent soft assertions
// emitted earlier in the test.
type Fixtures = {
  pageErrors: string[]
}

export const test = base.extend<Fixtures>({
  // `auto: true` ensures the listener and final assertion run for every
  // test in this suite—no need for specs to declare `pageErrors`
  // in its parameter list.
  pageErrors: [async ({ page }, use) => {
    const errors: string[] = []
    page.on('pageerror', (e) => errors.push(String(e)))
    await use(errors)
    expect.soft(errors, 'no uncaught JS errors during the test').toHaveLength(0)
  }, { auto: true }],
})

export { expect }
