// Generated by reviewqa. Single-page happy flow: navigate, walk, fill, submit, advance.
import { test, expect } from '@playwright/test'
const TARGET = 'https://www.spritecloud.com'

test.describe('WwwSpritecloudCom — browse journey', () => {
  // Shared setup: one navigation per test, and any uncaught JS error
  // during the test is collected so afterEach can fail the test on it.
  // This catches "the page silently broke" classes of bugs that no
  // single assertion would otherwise notice.
  let pageErrors: string[]
  test.beforeEach(async ({ page }) => {
    pageErrors = []
    page.on('pageerror', (e) => pageErrors.push(String(e)))
    await page.goto(TARGET)
  })
  test.afterEach(() => {
    expect.soft(pageErrors, 'no uncaught JS errors during the test').toHaveLength(0)
  })
  test('browse: full user journey (3 step(s))', async ({ page }) => {
    // Step 1 — visit https://www.spritecloud.com (intent: nav) — handled by beforeEach
    await expect(page).toHaveTitle(/spriteCloud - Test your software, not your reputation!/i)
    await expect(page.getByRole('heading', { level: 1, name: /Test your software, not your reputation\./i }).first()).toBeVisible()
    await expect.soft(page.getByAltText(/Company logo Ahold Dhaize/i).first()).toBeAttached()
    await expect.soft(page.getByAltText(/Company logo Heineken/i).first()).toBeAttached()
    await expect(page.getByRole('banner').first()).toBeVisible()

    // Step 2 — click "/guides" and land on the next page (intent: nav)
    {
      const link = page.locator('a[href="/guides"], [href="/guides"]').first()
      try {
        await link.click({ timeout: 3000 })
      } catch {
        // Link is in the DOM but not directly clickable (often a hover-only
        // dropdown menu item). Navigate by URL so the destination still gets
        // exercised instead of the whole spec hard-failing on the menu.
        await page.goto('https://www.spritecloud.com/guides')
      }
      await expect(page).toHaveURL(new RegExp('/guides$'))
    }
    await expect(page).toHaveTitle(/spriteCloud - Your Software Testing and QA partner/i)
    await expect.soft(page.locator('h2', { hasText: /Guides/i }).first()).toBeAttached()
    await expect(page.getByRole('list').first()).toBeVisible()

    // Step 3 — click "/about-us" and land on the next page (intent: nav)
    {
      const link = page.locator('a[href="/about-us"], [href="/about-us"]').first()
      try {
        await link.click({ timeout: 3000 })
      } catch {
        // Link is in the DOM but not directly clickable (often a hover-only
        // dropdown menu item). Navigate by URL so the destination still gets
        // exercised instead of the whole spec hard-failing on the menu.
        await page.goto('https://www.spritecloud.com/about-us')
      }
      await expect(page).toHaveURL(new RegExp('/about-us$'))
    }
    await expect(page).toHaveTitle(/About Us/i)
    await expect(page.getByRole('heading', { level: 1, name: /Testing is in our DNA\./i }).first()).toBeVisible()
  })
})
