// Generated by reviewqa. Single-page happy flow: navigate, walk, fill, submit, advance.
import { test, expect } from '@playwright/test'
const TARGET = 'https://www.spritecloud.com'

test.describe('WwwSpritecloudCom page happy flow', () => {
  test.beforeEach(async ({ page }) => { await page.goto(TARGET) })

  test('walks 1 component(s) on https://www.spritecloud.com', async ({ page }) => {
    // --- WwwSpritecloudCom (intent: nav) ---
    await expect(page.getByRole('banner').first()).toBeVisible()
    // Navigate via first same-origin link.
    {
      const link = page.locator('a[href="/contact"], [href="/contact"]').first()
      await link.click()
      await expect(page).toHaveURL(new RegExp('/contact$'))
    }
  })
})
