// Generated by reviewqa. Single-page happy flow: navigate, walk, fill, submit, advance.
import { test, expect } from '@playwright/test'
const TARGET = 'https://www.spritecloud.com'

test.describe('WwwSpritecloudCom — research journey', () => {
  test('research: full user journey (2 step(s))', async ({ page }) => {
    // Step 1 — visit https://www.spritecloud.com (intent: nav)
    await page.goto(TARGET)
    await expect(page).toHaveTitle(/spriteCloud - Test your software, not your reputation!/i)
    await expect(page.getByRole('heading', { level: 1, name: /Test your software, not your reputation\./i }).first()).toBeVisible()
    await expect(page.getByRole('banner').first()).toBeVisible()

    // Step 2 — direct goto "/case-study-grandvision" (not linked from the previous page; intent: nav)
    await page.goto('https://www.spritecloud.com/case-study-grandvision')
    await expect(page).toHaveURL(new RegExp('/case-study-grandvision$'))
    await expect(page).toHaveTitle(/Case Study - GrandVision/i)
    await expect(page.getByRole('heading', { level: 1, name: /GrandVision/i }).first()).toBeVisible()
  })
})
