// Generated by reviewqa. Single-page happy flow: navigate, walk, fill, submit, advance.
import { test, expect } from '@playwright/test'
const TARGET = 'https://www.spritecloud.com'

test.describe('WwwSpritecloudCom — research journey', () => {
  // Shared setup: one navigation per test, and any uncaught JS error
  // during the test is collected so afterEach can fail the test on it.
  // This catches "the page silently broke" classes of bugs that no
  // single assertion would otherwise notice.
  let pageErrors: string[]
  test.beforeEach(async ({ page }) => {
    pageErrors = []
    page.on('pageerror', (e) => pageErrors.push(String(e)))
    await page.goto(TARGET)
  })
  test.afterEach(() => {
    expect.soft(pageErrors, 'no uncaught JS errors during the test').toHaveLength(0)
  })
  test('research: full user journey (2 step(s))', async ({ page }) => {
    // Step 1 — visit https://www.spritecloud.com (intent: nav) — handled by beforeEach
    await expect(page).toHaveTitle(/spriteCloud - Test your software, not your reputation!/i)
    await expect(page.getByRole('heading', { level: 1, name: /Test your software, not your reputation\./i }).first()).toBeVisible()
    await expect.soft(page.getByAltText(/Company logo Ahold Dhaize/i).first()).toBeAttached()
    await expect.soft(page.getByAltText(/Company logo Heineken/i).first()).toBeAttached()
    await expect.soft(page.locator('meta[name="description"]')).toHaveAttribute('content', /spriteCloud is a software testing company based in Amsterdam, Netherlands\. We help companies and organisations ship robust and safe software\. We work as long term partners, or as interim solutions\./i)
    await expect.soft(page.locator('meta[property="og:title"]')).toHaveAttribute('content', /spriteCloud - Test your software, not your reputation!/i)
    await expect(page.getByRole('banner').first()).toBeVisible()

    // Step 2 — direct goto "/case-study-grandvision" (not linked from the previous page; intent: nav)
    await page.goto('https://www.spritecloud.com/case-study-grandvision')
    await expect(page).toHaveURL(new RegExp('/case-study-grandvision$'))
    await expect(page).toHaveTitle(/Case Study - GrandVision/i)
    await expect(page.getByRole('heading', { level: 1, name: /GrandVision/i }).first()).toBeVisible()
  })
})
