// Generated by reviewqa. Single-page happy flow: navigate, walk, fill, submit, advance.
import { test, expect } from '@playwright/test'
const TARGET = 'https://www.spritecloud.com'

test.describe('WwwSpritecloudCom — explore journey', () => {
  test('explore: full user journey (2 step(s))', async ({ page }) => {
    // Step 1 — visit https://www.spritecloud.com (intent: nav)
    await page.goto(TARGET)
    await expect(page).toHaveTitle(/spriteCloud - Test your software, not your reputation!/i)
    await expect(page.getByRole('heading', { level: 1, name: /Test your software, not your reputation\./i }).first()).toBeVisible()
    await expect(page.getByRole('banner').first()).toBeVisible()

    // Step 2 — click "/cybersecurity" and land on the next page (intent: nav)
    {
      const link = page.locator('a[href="/cybersecurity"], [href="/cybersecurity"]').first()
      try {
        await link.click({ timeout: 3000 })
      } catch {
        // Link is in the DOM but not directly clickable (often a hover-only
        // dropdown menu item). Navigate by URL so the destination still gets
        // exercised instead of the whole spec hard-failing on the menu.
        await page.goto('https://www.spritecloud.com/cybersecurity')
      }
      await expect(page).toHaveURL(new RegExp('/cybersecurity$'))
    }
    await expect(page).toHaveTitle(/spriteCloud - Penetration Testing/i)
    await expect(page.getByRole('heading', { level: 1, name: /Fully Tailored Cybersecurity\./i }).first()).toBeVisible()
  })
})
