// Generated by reviewqa. Single-page happy flow: navigate, walk, fill, submit, advance.
import { test, expect } from '@playwright/test'
const TARGET = 'https://www.spritecloud.com'

test.describe('WwwSpritecloudCom — browse journey', () => {
  test('browse: full user journey (3 step(s))', async ({ page }) => {
    // Step 1 — visit https://www.spritecloud.com (intent: nav)
    await page.goto(TARGET)
    await expect(page).toHaveTitle(/spriteCloud - Test your software, not your reputation!/i)
    await expect(page.getByRole('heading', { level: 1, name: /Test your software, not your reputation\./i }).first()).toBeVisible()
    await expect(page.getByRole('banner').first()).toBeVisible()

    // Step 2 — click "/guides" and land on the next page (intent: nav)
    {
      const link = page.locator('a[href="/guides"], [href="/guides"]').first()
      try {
        await link.click({ timeout: 3000 })
      } catch {
        // Link is in the DOM but not directly clickable (often a hover-only
        // dropdown menu item). Navigate by URL so the destination still gets
        // exercised instead of the whole spec hard-failing on the menu.
        await page.goto('https://www.spritecloud.com/guides')
      }
      await expect(page).toHaveURL(new RegExp('/guides$'))
    }
    await expect(page).toHaveTitle(/spriteCloud - Your Software Testing and QA partner/i)
    await expect(page.getByRole('list').first()).toBeVisible()

    // Step 3 — click "/about-us" and land on the next page (intent: nav)
    {
      const link = page.locator('a[href="/about-us"], [href="/about-us"]').first()
      try {
        await link.click({ timeout: 3000 })
      } catch {
        // Link is in the DOM but not directly clickable (often a hover-only
        // dropdown menu item). Navigate by URL so the destination still gets
        // exercised instead of the whole spec hard-failing on the menu.
        await page.goto('https://www.spritecloud.com/about-us')
      }
      await expect(page).toHaveURL(new RegExp('/about-us$'))
    }
    await expect(page).toHaveTitle(/About Us/i)
    await expect(page.getByRole('heading', { level: 1, name: /Testing is in our DNA\./i }).first()).toBeVisible()
  })
})
