/* reviewqa quality report
 * Weak / missing locators on this page:
 *   - note: using <placeholder> as locator — no data-testid on the input
 *   - SKIP: input on line 24 has no stable locator — add data-testid
 * Add data-testid to these elements for stable tests.
 */
// Generated by reviewqa. Single-page happy flow: navigate, walk, fill, submit, advance.
import { test, expect } from '@playwright/test'
const TARGET = 'https://www.spritecloud.com'

test.describe('WwwSpritecloudCom — convert journey', () => {
  // Shared setup: one navigation per test, and any uncaught JS error
  // during the test is collected so afterEach can fail the test on it.
  // This catches "the page silently broke" classes of bugs that no
  // single assertion would otherwise notice.
  let pageErrors: string[]
  test.beforeEach(async ({ page }) => {
    pageErrors = []
    page.on('pageerror', (e) => pageErrors.push(String(e)))
    await page.goto(TARGET)
  })
  test.afterEach(() => {
    expect.soft(pageErrors, 'no uncaught JS errors during the test').toHaveLength(0)
  })
  test('convert: full user journey (1 step(s))', async ({ page }) => {
    // Step 1 — visit https://www.spritecloud.com (intent: form) — handled by beforeEach
    await expect(page).toHaveTitle(/spriteCloud - Test your software, not your reputation!/i)
    await expect(page.getByRole('heading', { level: 1, name: /Test your software, not your reputation\./i }).first()).toBeVisible()
    await expect.soft(page.getByAltText(/Company logo Ahold Dhaize/i).first()).toBeAttached()
    await expect.soft(page.getByAltText(/Company logo Heineken/i).first()).toBeAttached()
    await expect(page.getByRole('banner').first()).toBeVisible()
    await expect(page.getByRole('button', { name: 'Submit' }).first()).toBeVisible()
    // Fill form
    // note: using <placeholder> as locator — no data-testid on the input
    await page.getByPlaceholder('Your email address').first().fill('test@example.com')
    // SKIP: input on line 24 has no stable locator — add data-testid
    await page.getByRole('button', { name: 'Submit' }).first().click()
    await expect(page.locator('text=/error|failed/i')).toHaveCount(0)
  })
})
