/**
 * Generated by reviewqa.
 *
 * Interaction-state visual baselines for https://www.spritecloud.com/on-demand. For each
 * primary interactive element on the page, screenshots default /
 * hover / focus states are captured and diffed against committed
 * PNGs. Catches subtle visual regressions invisible to viewport-level
 * baselines.
 *
 * First run captures baselines; subsequent runs diff:
 *   npm run test:visual-update  # capture / refresh
 *   npx playwright test --grep @kind:visual-state
 *
 * Filter: `npx playwright test --grep @kind:visual-state`
 */
import { test, expect } from '@playwright/test'

const STATES = ['default', 'hover', 'focus'] as const

test.describe.configure({ mode: 'parallel' })
test.describe('WwwSpritecloudCom — Interaction-state visual checks @ https://www.spritecloud.com/on-demand', () => {
  test('@kind:visual-state @smoke Primary CTA—default, hover, and focus states', async ({ page }) => {
    await page.goto('/on-demand')
    await page.waitForLoadState('networkidle').catch(() => {})
    const target = page.getByRole('link').first()
    if (await target.count() === 0) {
      test.skip(true, 'No primary call-to-action link found on the page')
      return
    }

    for (const state of STATES) {
      switch (state) {
        case 'hover':
          await target.hover().catch(() => {})
          break
        case 'focus':
          await target.focus().catch(() => {})
          break
        default:
          // Default state (no interaction)
          break
      }
      await expect(target).toHaveScreenshot(`wwwspritecloudcom-cta-${state}.png`, {
        maxDiffPixelRatio: 0.02,
        animations: 'disabled',
      })
    }
  })
})
