// Generated by reviewqa. Shared Playwright fixtures for the generated
// e2e suite. All `*.spec.ts` files in this directory import `test` and
// `expect` from here instead of from `@playwright/test` directly, so
// every spec inherits the page-error tracking + baseline assertions
// without re-declaring them.
import { test as base, expect } from '@playwright/test'

// `pageErrors` is a custom fixture that wraps the standard `page` fixture. It installs a `pageerror` listener at the start of each test and ensures no uncaught errors remain at the end.
//
// `expect.soft` is used for the final assertion, so uncaught JavaScript errors are reported without failing earlier assertions.
type Fixtures = {
  pageErrors: string[]
}

export const test = base.extend<Fixtures>({
  // `auto: true` so the listener and the final assertion run for every
  // test in this suite without the spec having to declare `pageErrors`
  // in its function-parameter destructuring.
  pageErrors: [async ({ page }, use) => {
    const errors: string[] = []
    page.on('pageerror', (e) => errors.push(String(e)))
    await use(errors)
    expect.soft(errors, 'no uncaught JS errors during the test').toHaveLength(0)
  }, { auto: true }],
})

export { expect }
