/**
 * Generated by quail.
 *
 * Auth-expiry baseline for https://www.spritecloud.com/test-automation. Asserts the page handles an
 * expired session gracefully — when storage state is cleared mid-
 * journey, the next action surfaces a sign-in prompt or auth-expiry
 * notice rather than blank-screening or 500-ing.
 *
 * Filter: `npx playwright test --grep @kind:auth-expiry`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('Spritecloud — authentication expiry handling (auth-expiry scenario)', () => {
  test('Clearing session cookies mid-journey results in a proper sign-in prompt instead of blank screen or error', async ({ page, context }) => {
    await page.goto('/test-automation', { waitUntil: 'domcontentloaded' })
    // Simulate the user's session expiring server-side.
    await context.clearCookies()
    await page.evaluate(() => {
      try { localStorage.removeItem('token'); sessionStorage.clear() } catch {}
    })
    // Navigate to a link from the landing — the next request will
    // arrive with no auth.
    const internalLink = page.locator('a[href^="/"]:not([href^="//"])').first()
    if (await internalLink.count() === 0) test.skip()
    await internalLink.click({ timeout: 5000 }).catch(() => {})
    await page.waitForLoadState('domcontentloaded').catch(() => {})
    // The page should render something — either a sign-in form, an
    // auth-expiry notice, or the public version of the content. NOT
    // a blank screen and NOT a stack trace.
    await expect(page.locator('h1, [role="heading"][aria-level="1"], form, [role="alert"]').first()).toBeVisible({ timeout: 10_000 })
    const body = await page.locator('body').innerText().catch(() => '')
    expect.soft(body.toLowerCase()).not.toContain('traceback')
    expect.soft(body.toLowerCase()).not.toContain('stack trace')
  })
})
