/**
 * Generated by reviewqa.
 *
 * Performance baseline for https://www.spritecloud.com/cybersecurity. Asserts the page loads under
 * the configured SLO (default 3000ms; override via PERF_SLO_MS env).
 * Single-request latency check — NOT load testing.
 *
 * Filter: `npx playwright test --grep @kind:perf`
 */
import { test, expect } from '@playwright/test'

const SLO_MS = Number(process.env.PERF_SLO_MS ?? 3000)

test.describe.configure({ mode: 'parallel' })
test.describe('Spritecloud cybersecurity page loads under performance SLO', () => {
  test(`loads under ${SLO_MS}ms (performance smoke test)`, async ({ page }) => {
    const start = Date.now()
    await page.goto('/cybersecurity', { waitUntil: 'load' })
    const elapsed = Date.now() - start
    console.log(`Page loaded in ${elapsed}ms (SLO: ${SLO_MS}ms)`)
    expect.soft(elapsed, `Load time ${elapsed}ms exceeds SLO of ${SLO_MS}ms`).toBeLessThan(SLO_MS)
    // Hard fail at 2x SLO so a deeply broken site still surfaces.
    expect(elapsed).toBeLessThan(SLO_MS * 2)
  })
})
