/**
 * Generated by quail.
 *
 * Race-condition baseline for https://www.ing.nl/zakelijk. When the page exposes a
 * form, asserts the form does not double-submit under a fast
 * double-click — a regression that costs real money on payment /
 * checkout flows and silently inflates contact form noise. Emitted
 * only when probe detected a <form>.
 *
 * Filter: `npx playwright test --grep @kind:race`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('ING — race condition check at https://www.ing.nl/zakelijk', () => {
  test('form handles rapid double-submit without duplication', async ({ page }) => {
    await page.goto('/zakelijk', { waitUntil: 'domcontentloaded' })
    const form = page.locator('form').first()
    if (await form.count() === 0) test.skip()
    const submit = form.locator('button[type="submit"], input[type="submit"]').first()
    if (await submit.count() === 0) test.skip()
    // Fire two clicks back-to-back without waiting for navigation.
    await Promise.allSettled([
      submit.click({ noWaitAfter: true }),
      submit.click({ noWaitAfter: true }),
    ])
    await page.waitForLoadState('domcontentloaded').catch(() => {})
    // Asserts no more than one success indicator appears after rapid double-submit.
    const indicators = page.locator('text=/success|thanks|received|submitted/i')
    const count = await indicators.count()
    expect.soft(count, `found ${count} success indicators after double-submit — likely a duplicate-submit error`).toBeLessThanOrEqual(1)
  })
})
