/**
 * Generated by quail.
 *
 * Security header smoke for https://www.spritecloud.com. Hits the origin and checks
 * presence of the headers most browsers rely on to enforce baseline
 * web security: HSTS, CSP, X-Frame-Options (or CSP frame-ancestors),
 * X-Content-Type-Options, Referrer-Policy.
 *
 * Soft assertions — a missing header surfaces in the report without
 * cascading the rest of the suite. The hard assertion is "we got SOME
 * response at all".
 *
 * Filter: `npx playwright test --grep @kind:security`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('Spritecloud — security headers on https://www.spritecloud.com', () => {
  test('baseline security headers present', async ({ request }) => {
    const response = await request.get('https://www.spritecloud.com')
    expect(response.status(), 'origin responds').toBeLessThan(500)
    const headers = response.headers()

    expect.soft(headers['strict-transport-security'], 'HSTS header missing').toBeTruthy()
    const csp = headers['content-security-policy'] || ''
    expect.soft(csp, 'CSP header missing').toBeTruthy()
    const xfo = headers['x-frame-options']
    const cspFrameAncestors = /frame-ancestors/i.test(csp)
    expect.soft(xfo || cspFrameAncestors, 'missing clickjacking protection (X-Frame-Options or CSP frame-ancestors)').toBeTruthy()
    expect.soft(headers['x-content-type-options'], 'X-Content-Type-Options header missing').toBe('nosniff')
    expect.soft(headers['referrer-policy'], 'Referrer-Policy header missing').toBeTruthy()
  })
})
