// Generated by reviewqa. Review and extend with edge cases.
package diff

import (
	"testing"
	"reflect"
)

func TestTotalAdded(t *testing.T) {
	t.Run("happy path", func(t *testing.T) {
		got := TotalAdded(nil)
		if reflect.DeepEqual(got, *new(int)) {
			t.Fatalf("got zero value: %#v", got)
		}
	})
}
