/**
 * Generated by quail.
 *
 * Visual baselines for interaction states (default, hover, focus) of primary interactive elements on https://www.spritecloud.com/cybersecurity. Screenshots are compared against committed PNGs to catch subtle visual regressions invisible to full-page screenshots.
 *
 * First run captures baselines; later runs compare against them:
 *   npm run test:visual-update  # update baselines
 *   npx playwright test --grep @kind:visual-state
 *
 * Run with: npx playwright test --grep @kind:visual-state
 */
import { test, expect } from '@playwright/test'

const STATES = ['default', 'hover', 'focus'] as const

test.describe.configure({ mode: 'parallel' })
test.describe('Spritecloud — visual states (default, hover, focus) @ https://www.spritecloud.com/cybersecurity', () => {
  test('@kind:visual-state @smoke primary CTA in all states', async ({ page }) => {
    await page.goto('/cybersecurity')
    await page.waitForLoadState('networkidle').catch(() => {})
    const target = page.getByRole('link').first()
    if (await target.count() === 0) {
      test.skip(true, 'no primary CTA detected on this page')
      return
    }

    for (const state of STATES) {
      switch (state) {
        case 'hover':
          await target.hover().catch(() => {})
          break
        case 'focus':
          await target.focus().catch(() => {})
          break
        default:
          // no interaction — default state
          break
      }
      await expect(target).toHaveScreenshot(`spritecloud-cta-${state}.png`, {
        maxDiffPixelRatio: 0.02,
        animations: 'disabled',
      })
    }
  })
})
