/**
 * Generated by reviewqa.
 *
 * Accessibility landmark structure for https://www.spritecloud.com/cybersecurity. Asserts the
 * page exposes the basic landmark scaffold screen readers depend on:
 *   - exactly one <main> (or [role=main])
 *   - exactly one <h1>
 *   - <nav> or [role=navigation] present
 *   - no focusable elements inside [aria-hidden=true]
 *
 * Filter: `npx playwright test --grep @kind:a11y-landmarks`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('Spritecloud cybersecurity page accessibility landmark structure', () => {
  test('contains exactly one main region, one h1, and one nav region', async ({ page }) => {
    await page.goto('/cybersecurity')

    const mains = await page.locator('main, [role="main"]').count()
    expect.soft(mains, `expected exactly one <main> region`).toBe(1)

    const h1s = await page.locator('h1').count()
    expect.soft(h1s, `expected exactly one <h1>`).toBe(1)

    const navs = await page.locator('nav, [role="navigation"]').count()
    expect.soft(navs, `expected at least one <nav> region`).toBeGreaterThanOrEqual(1)
  })

  test('no focusable elements inside aria-hidden regions', async ({ page }) => {
    await page.goto('/cybersecurity')
    const hiddenFocusables = await page.locator('[aria-hidden="true"]').locator('a, button, input, select, textarea, [tabindex]:not([tabindex="-1"])').count()
    expect.soft(hiddenFocusables, `${hiddenFocusables} focusable elements inside aria-hidden — confusing for screen readers`).toBe(0)
  })
})
