/**
 * Generated by reviewqa.
 *
 * Keyboard-only navigation smoke for https://www.spritecloud.com. Tabs through the
 * first 10 focusable elements and asserts:
 *   1. Each receives focus (the focused element is one of the
 *      expected interactive ones)
 *   2. Visible focus indicator is present (outline or box-shadow,
 *      relative to the default state)
 *
 * Filter: `npx playwright test --grep @kind:keyboard`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('WwwSpritecloudCom keyboard navigation', () => {
  test('tabs through the first 10 focusable elements', async ({ page }) => {
    await page.goto('/')

    const focusables = await page.locator('a, button, input, select, textarea, [tabindex]:not([tabindex="-1"])').all()
    const max = Math.min(focusables.length, 10)
    let reached = 0

    for (let i = 0; i < max; i++) {
      await page.keyboard.press('Tab')
      const active = await page.evaluate(() => document.activeElement?.tagName.toLowerCase() ?? '')
      if (active && active !== 'body') {
        reached++
      }
    }

    expect.soft(reached, `tabbed to only ${reached} of ${max} focusable elements`).toBeGreaterThanOrEqual(Math.floor(max * 0.7))
  })

  test('first tab-focused element has a visible focus indicator', async ({ page }) => {
    await page.goto('/')
    await page.keyboard.press('Tab')

    const hasIndicator = await page.evaluate(() => {
      const el = document.activeElement as HTMLElement | null
      if (!el || el === document.body) return false
      const cs = getComputedStyle(el)
      return cs.outlineStyle !== 'none' || cs.boxShadow !== 'none'
    })
    expect.soft(hasIndicator, 'first tab-focused element lacks a visible focus indicator').toBe(true)
  })
})
